version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Freightbills123"
      ACCEPT_EULA: "Y"